name: "Cachix"

on:
  pull_request:
  push:

jobs:
  push-cachix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: "${{ secrets.CACHIX_NAME }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: SSH Key
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 700 ~/.ssh/id_ed25519
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - name: Build syoch-robotics library
        run: nix build .
